# CPU-only switch (uncomment to build without GPU support).
# CPU_ONLY := 1

# Set custom include in library paths
INCLUDE_DIRS := /usr/local/include 
LIBRARY_DIRS := /usr/local/lib \
                /usr/lib 

BUILD_DIR := build

# Uncomment for debugging.
# DEBUG := 1
